### PR TITLE
Debian Upgrade and Dockerfile Installations

### PR DESCRIPTION
**Pull request by SantiiRepair**

### CODE REVIEW

**Comment by vitordino** [comment]
this project is a bit abandoned, were you able to run with just these changes?

i do think code-wise this is correct: at least get us closer to a working state.

but i think there will be some greater changes..
eg.: the docker image this repo build upon (`hlds-amxmodx`) has been removed from docker hub (probably because of the new pricing etc)

are you interested on maintaining? unfortunately i don’t have the bandwidth right now

a starting point would likely be looking for the existing docker hub images, or other repos

**Comment by SantiiRepair** [comment]
I only managed to compile the image with those changes, I had to run it without docker using rehlds, if you want I can add those new changes

**Comment by SantiiRepair** [comment]
If you want me to be the maintainer I have no problem with that.

**Comment by vitordino** [comment]
invited you as a maintainer, i can also transfer this repo if you prefer to (:

**Pull request merged**
